version: "3.2"

services:
  db:
    image: postgres:12.1
    env_file:
      - .envs/.local/.postgres
    ports:
      - 5432:5432

  base:
    build:
      dockerfile: docker/local/base/Dockerfile
      context: .
    image: apollo-base

  app:
    build:
      dockerfile: docker/local/backend/Dockerfile
      context: .
    env_file:
      - .envs/.local/.django
      - .envs/.local/.postgres
    ports:
      - 8000:8000
    depends_on:
      - db
