[tool.poetry]
name = "helios-backend"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
Django = "^=3.0.2"
django-extensions = "^=2.2.5"
daphne = "^2.4.1"
django-environ = "^=0.4.5"
psycopg2-binary = "^=2.8.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
