version: 2
dependencies:
  pre:
    - pip install --upgrade pip
    - pip install docker-compose
jobs:
  build:
    machine: true
    # machine:
    #   pre:
    #     - curl -sSL https://s3.amazonaws.com/circle-downloads/install-circleci-docker.sh | bash -s -- 1.10.0
    #     - pip install --upgrade pip
    #     - pip install docker-compose
    
      # services:
      #   - docker
      
    steps:
      - checkout
      - run:
          name: Run backend tests
          command: |
            docker-compose -f docker-compose-ci.yml run --rm app python manage.py test --settings config.settings.test
  
