# Generated by Django 3.0.4 on 2020-04-01 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("elections", "0002_remove_elections"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
