# Generated by Django 3.0.5 on 2020-05-03 19:50

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_add_votes_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='state',
            field=django_fsm.FSMField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='election',
            name='frozen_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='opened_at',
            field=models.DateTimeField(null=True),
        ),
    ]
