# Generated by Django 3.0.5 on 2020-05-09 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0005_election_state"),
    ]

    operations = [
        migrations.RenameField(
            model_name="election", old_name="frozen_at", new_name="closed_at",
        ),
    ]
