# Generated by Django 3.0.4 on 2020-04-06 19:57

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0005_election_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="election",
            name="state",
            field=django_fsm.FSMField(default="0", max_length=50),
        ),
    ]
