# Generated by Django 3.0.4 on 2020-05-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0006_auto_20200406_1957"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="frozen_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="election",
            name="opened_at",
            field=models.DateTimeField(null=True),
        ),
    ]
