# Generated by Django 3.0.6 on 2020-05-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_frozen_to_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='public_key',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='secret_key',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
