# Generated by Django 3.0.6 on 2020-05-18 18:16

from django.db import migrations, models
import django.utils.timezone
import django_utils.choices


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0007_election_keys"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoterAuthorizationRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (0, django_utils.choices.Choice(0, "EXACT")),
                            (1, django_utils.choices.Choice(1, "REGEX")),
                        ]
                    ),
                ),
                ("value", models.CharField(max_length=100)),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorization_rules",
                        to="elections.Election",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="answer",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="question",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
