# Generated by Django 3.0.6 on 2020-05-24 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0008_voterauthorizationrule"),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="vote", name="unique_answer_author",),
        migrations.AddField(
            model_name="vote",
            name="answer_ciphertext",
            field=models.CharField(default=None, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vote",
            name="question",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="elections.Question",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vote",
            name="answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="elections.Answer",
            ),
        ),
    ]
