# Generated by Django 3.0.6 on 2020-05-23 14:43

from django.db import migrations, models
import django_utils.choices


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0008_voterauthorizationrule"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="visibility",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, django_utils.choices.Choice(0, "PRIVATE")),
                    (1, django_utils.choices.Choice(1, "PUBLIC")),
                ],
                default=1,
            ),
            preserve_default=False,
        ),
    ]
