name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
      - github-packages

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build images
        run: |
          docker-compose --file docker-compose-ci.yml build base app web

      - name: Run black on backend
        run: |
          docker-compose --file docker-compose-ci.yml run --rm app black --check .

      - name: MyPy static analysis
        run: |
          docker-compose --file docker-compose-ci.yml run --rm app mypy apollo

      - name: Run backend tests
        run: |
          docker-compose --file docker-compose-ci.yml run --rm app python manage.py test --settings config.settings.test

      - name: Log into registry
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          echo "${{ secrets.DOCKER_TOKEN }}"

      - name: Tag & Push images
        if: github.event_name == 'push'
        run: |
          docker tag apollo-base votifica/${{ github.repository }}/base:latest
          docker tag apollo_app votifica/${{ github.repository }}/app:latest
          docker tag apollo_web votifica/${{ github.repository }}/web:latest

          docker push votifica/${{ github.repository }}/base:latest
          docker push votifica/${{ github.repository }}/app:latest
          docker push votifica/${{ github.repository }}/web:latest
